apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: configuration-anomaly-detection-jtnm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: configuration-anomaly-detection-jtnm
    app.kubernetes.io/part-of: configuration-anomaly-detection
  name: configuration-anomaly-detc2pz
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: configuration-anomaly-detection-jtnm
    weight: 100
status: {}
