apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: configuration-anomaly-detection-jtnm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: configuration-anomaly-detection-jtnm
    app.kubernetes.io/part-of: configuration-anomaly-detection
  name: configuration-anomaly-detection-jtnm
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: configuration-anomaly-detection-jtnm
status:
  loadBalancer: {}
